// recode/JDP-react/src/page/Component/widget/commonLists.jsx
import React, { Component, PropTypes } from 'react';
import pureRender from 'pure-render-decorator';
import { History, Link } from 'react-router';
import Immutable, { is, fromJS } from 'immutable';

import store from '../../Redux/Store';

import {listFilterCenter, listFilterDepartment, listInitDepartMents, listFilterType,
listFilterState, listFilterRisk, listFilterProject, detailSearchResult} from '../../Redux/Action';


import '../../Style/sass/list';

export class CommonLists extends Component {
  constructor(props, context) {
    super(props, context);

    this.state = {
      searchJson : null
    }
  }

  //自定义事件回调父级事件
  // _toVisited() {
  //   console.log(this.props)
  //   this.props.onVisited && this.props.onVisited(true);
  // }

  //早期dispatch
  // _click(event) {
  //   if(this.props.configs.touch) {
  //     let {configs} = this.props;
  //     this.props.selectToStrings({type: configs.type, name: configs.name});
  //   }
  // }

  goToxmxq(item) {
    store.dispatch(detailSearchResult(item));
  }

  addFilter(item, index) {
    let _this = this;
    let id = this.props.routeParams.id;
    let optionsId = parseInt(item.optionsId);

    switch(id) {
      case "1":
        if(index == 0) {
          // store.dispatch(listInitDepartMents());
          store.dispatch(listFilterCenter(item));
          this.props.router.push({
            pathname : '/xmsx'
          });
          return;
        } else {
          store.dispatch(listInitDepartMents());
          store.dispatch(listFilterCenter(item));
        }
      break;

      case "2":
        store.dispatch(listFilterType(item));
      break;

      case "3":
        store.dispatch(listFilterState(item));
      break;

      case "4":
        store.dispatch(listFilterRisk(item));
      break;

      case "5":
        store.dispatch(listFilterProject(item));
      break;
    }
    if(id == "1") {
      this.props.router.push({
        pathname: `/xmsx/option/1/${item.choiceId}`
      })
    } else {
      this.props.router.push({
        pathname: '/xmsx'
      })
    }
  }

  addFilterDepart(item) {
    store.dispatch(listFilterDepartment(item));

    // 因为没有通过Link路由所以，this.props.router属性不会存在。
    //
    // this.props.router.push({
    //   pathname : '/xmsx'
    // });
  }

  componentWillMount() {
    let searchJson = Immutable.Map(store.getState().searchModule).toJS();
    searchJson = searchJson.data.filter?searchJson.data.filter:null;
    this.setState({
      searchJson: searchJson
    })
  }

  subNumber(index) {
    this.props.onClick(index);
  }

  render() {
    let {list, type} = this.props.configs;
    let {searchJson} = this.state;
    // 早期jsx版本
    // return <ul>
    //   {
    //     list.length > 0?list.map((item, index) => {
    //       return (
    //         <div key={index} className="nav-list-item" onClick={(event) => this._click(event)}>
    //           {item.to?<Link to={`${item.to}`}>
    //             {type=='main'?<em className={`${item.iconClass}`}></em>:null}
    //             <span>{item.text}</span>
    //             {type=='listNav'?<em className="icon iconn-5 icon-info"></em>:null}
    //           </Link>:<span className={type == 'memberList'?'navListItemTitle':null}>
    //             {type=='memberList'?<strong>{item.name}<span>{item.text}</span></strong>:null}
    //           </span>}
    //         </div>
    //       )
    //     }):null
    //   }
    // </ul>
    //
    // 上线版本
    //
    return (
      <ul>
        {
          list.length > 0?list.map((item, index) => {
            return (
              <li key={index}>
                {type=="eventRes"?<div key={index} className={(this.props.action)&&(this.props.subIndex==index)?"navListItemTitle itemAction":"navListItemTitle"} onClick={() => {this.subNumber(index)}}>
                  <strong>{index+1}.{item.name}</strong>
                  <span>{item.text}</span>
                </div>:null}
                {type=='main'?<div key={index} className="nav-list-item">
                  <Link to={`${item.to}`}>
                    <em className={`${item.iconClass}`}></em>
                    <span>{item.text}</span>
                    <em className="icon iconn-5 icon-info"></em>
                  </Link>
                </div>:null}
                {type=='xmlx'?<div key={index} className="nav-list-item">
                  <Link to={`${item.to}`}>
                    <span>{item.text}</span>
                    <em className="icon iconn-5 icon-info"></em>
                  </Link>
                </div>:null}
                {type=="sxjg"?<div key={index} className="nav-list-item mr80" onClick={() => this.goToxmxq(item)}>
                  <Link to={`${item.to}`}>
                    <span>{item.text}</span>
                    <em className="icon iconn-5 icon-info"></em>
                  </Link>
                </div>:null}
                {type=="gzl"?<div key={index} className="nav-list-item">
                  <Link to={`${item.to}`}>
                    <span>{item.text}</span>
                    <em className="icon iconn-5 icon-info"></em>
                  </Link>
                </div>:null}
                {type=="xmsx"?<div key={index} className="nav-list-item">
                  <Link to={`${item.to}`}>
                    <span>{item.text}</span>
                    <em className="icon iconn-5 icon-info"></em>
                  </Link>
                </div>:null}
                {type=="xmsxVisited"?<div key={index} className="nav-list-item">
                  <Link to={`${item.to}`}>
                    <span>{item.text}</span>
                    <em className="icon iconn-5 icon-info"></em>
                    {/*
                      reducer数据结构改写，注释掉
                      {(index == 0)?(searchJson.centerName?<strong id={`${searchJson.center}_${searchJson.departId}`}>{searchJson.centerName}{searchJson.departName?<span>/</span>:null}{searchJson.departName}</strong>:null):null}
                      {(index == 1)?(searchJson.typeName?<strong id={searchJson.typeId}>{searchJson.typeName}</strong>:null):null}
                      {(index == 2)?(searchJson.stateName?<strong id={searchJson.stateId}>{searchJson.stateName}</strong>:null):null}
                      {(index == 3)?(searchJson.riskName?<strong id={searchJson.riskId}>{searchJson.riskName}</strong>:null):null}
                      {(index == 4)?(searchJson.projectName?<strong id={searchJson.projectId}>{searchJson.projectName}</strong>:null):null}
                    */}
                    {item.choiceCenter?(<strong>{item.choiceCenter}{item.choiceDepart?<span>/</span>:null}{item.choiceDepart}</strong>):null}
                    {item.choiceText?<strong>{item.choiceText}</strong>:null}
                  </Link>
                </div>:null}
                {type=="lxxx"?<div key={index} className="nav-list-item" onClick={() => this.addFilter(item, index)}>
                  <span>{item.text}</span>
                  <em className="icon iconn-5 icon-info"></em>
                </div>:null}
                {type=="bmsx"?<div key={index} className="nav-list-item" onClick={() => this.addFilterDepart(item)}>
                  <Link to={`${item.to}`}>
                    <span>{item.text}</span>
                  </Link>
                </div>:null}
                {type=="xmcy"?<div key={index} className="navListItemTitle">
                  <strong>{index+1}.{item.name}</strong>
                  <span>{item.text}</span>
                </div>:null}
              </li>
            )
          }):null
        }
      </ul>
    )
  }
}

export default CommonLists;

// recode/JDP-vue 3/src/components/widget/commonLists.vue
<template>
  <ul @touchstart=touchstart($event) @touchmove=touchmove($event) @touchend=touchend($event)>
    <li v-if="configs.type == 'main'" v-for="item in configs.list" class="nav-list-item">
      <router-link :to="item.to">
        <em :class="[item.iconClass]"></em>
        <span>{{item.text}}</span>
        <em class="icon iconn-5 icon-info"></em>
      </router-link>
    </li>
    <li v-if="configs.type == 'xmlx'" v-for="item in configs.list" class="nav-list-item">
      <router-link :to="item.to">
        <span>{{item.text}}</span>
        <em class="icon iconn-5 icon-info"></em>
      </router-link>
    </li>
    <li v-if="configs.type == 'sxjg'" @click="goToxmxq(item)" v-for="item in configs.list" class="nav-list-item mr80">
      <span>{{item.text}}</span>
      <em v-if="bToDetail" class="icon iconn-5 icon-info"></em>
    </li>
    <li v-if="configs.type == 'gzl'" v-for="item in configs.list" class="nav-list-item">
      <router-link :to="item.to">
        <span>{{item.text}}</span>
        <em class="icon iconn-5 icon-info"></em>
      </router-link>
    </li>
    <li v-if="configs.type == 'xmsx'" v-for="item in configs.list" class="nav-list-item">
      <router-link :to="item.to">
        <span>{{item.text}}</span>
        <em class="icon iconn-5 icon-info"></em>
      </router-link>
    </li>
    <li v-if="configs.type == 'xmsxVisited'" v-for="item in configs.list" class="nav-list-item">
      <router-link :to="item.to">
        <span>{{item.text}}</span>
        <em class="icon iconn-5 icon-info"></em>
        <strong v-if="item.choiceCenter">{{item.choiceCenter}}<span v-if="item.choiceDepart">/</span>{{item.choiceDepart}}</strong>
        <strong v-if="item.choiceText">{{item.choiceText}}</strong>
      </router-link>
    </li>
    <li v-if="configs.type == 'lxxx'" @click="addFilter(item, index)" v-for="(item, index) in configs.list" class="nav-list-item">
      <span>{{item.text}}</span>
      <em class="icon iconn-5 icon-info"></em>
    </li>
    <li v-if="configs.type == 'bmsx'" @click="addFilterDepart(item)" v-for="item in configs.list" class="nav-list-item">
      <span>{{item.text}}</span>
    </li>
    <li v-if="configs.type == 'xmcy'" v-for="(item, index) in configs.list" class="navListItemTitle">
      <strong>{{index+1}}.{{item.name}}</strong>
      <span>{{item.text}}</span>
    </li>
  </ul>
</template>

<script>
import { mapState } from 'vuex';
import store from '../../vuex';
export default {
  name: 'lists',
  props:['configs'],
  computed:{
    ...mapState({
      bToDetail:state=>state.filterByTable.bToDetail

    })
  },
  methods: {
    addFilter(item, index){
      let _this = this;
      let optionsId = parseInt(item.optionsId);
      switch(optionsId){
        case 1:
          if(index == 0){
            this.$router.push({path:'/xmsx'});
            store.commit('filterCenter', {
              centerName: item.text,
              centerId: item.choiceId,
              filterCenter: true
            });
            store.commit('filterDepartment', {
              departId: 0,
              departName: '全部',
              filterDepartment: true
            });
            return;
          }else{
            store.commit('initDepartMents');
          }
          store.commit('filterCenter', {
            centerName: item.text,
            centerId: item.choiceId,
            filterCenter: true
          });
          break;
        case 2:
          store.commit('filterType', {
            typeId: item.choiceId,
            typeName: item.text,
            filterType: true
          });
          break;
        case 3:
          store.commit('filterState', {
            stateId: item.choiceId,
            stateName: item.text,
            filterState: true,
          });
          break;
        case 4:
          store.commit('filterRisk', {
            riskId: item.choiceId,
            riskName: item.text,
            filterRisk: true,
          });
          break;
        case 5:
          store.commit('filterProject', {
            projectId: item.choiceId,
            projectName: item.text,
            filterProject: true
          });
          break;
      }
      if(optionsId == 1){
        this.$router.replace({path:`/xmsx/option/1/${item.choiceId}`});
      }else{
        _this.$router.push({path:'/xmsx'});
      }
    },
    addFilterDepart(item){
      store.commit('filterDepartment', {
        departId: item.departmentId,
        departName: item.text,
        filterDepartment: true
      });
      this.$router.push({path:'/xmsx'});
    },
    goToxmxq(item){
      if(!this.bToDetail)return;
      store.commit('setCurProject', {
        curName: item.text,
        curProjectId: item.projectId
      });
      this.$router.push({path:'/xmsx/xmxq'});
    },
    touchstart(event){
      this.startY = event.touches[0].clientY;
    },
    touchmove(event){
      this.moveY = event.touches[0].clientY;
    },
    touchend(event){
      let _this = this;
      if(!this.configs.isCanLoad)return;
      if((this.startY - this.moveY) >= 60){
        // store.dispatch('setIsLoad', true);
        // store.dispatch("loading", 1);
        setTimeout(function (){
          switch(_this.$route.name){
            case 'xmcy':
              store.dispatch('filterMembersList', true);
              break;
            case 'bmsx':
              //store.dispatch('filterDepartList', true);
              break;
            case 'sxjg':
              store.dispatch('filterProjectList', true);
              break;
          }
        }, 100);

      }else{
        store.dispatch('setIsLoad', false);
      }
    }
  }
}
</script>

<style lang='sass'>
@import '../../assets/sass/list.scss';
</style>
