// recode/JDP-react 2/src/page/Component/xmsx.jsx
import React, { Component, PropTypes } from 'react';
import pureRender from 'pure-render-decorator';
import { History, Link } from 'react-router';
import Immutable, { is, fromJS } from 'immutable';

import store from '../Redux/Store';

import {detailSearchResult} from '../Redux/Action';

import CommonLists from './widget/commonLists';
import Connect from './connect/template';

class Xmsx extends Component {
  constructor(props, context) {
    super(props, context);

    this.state = {
      showFilter: true,
      showSearch: false,
      searchText: '',
      filterData: false,
      configs: {
        type: 'xmsx',
        list: [
          {
            to: '/xmsx/option/1',
            text: '选择中心/部门'
          },
          {
            to: '/xmsx/option/2',
            text: '选择类型'
          },
          {
            to: '/xmsx/option/3',
            text: '选择阶段'
          },
          {
            to: '/xmsx/option/4',
            text: '选择风险类型'
          },
          {
            to: '/xmsx/option/5',
            text: '选择状态类型'
          },
        ]
      },
      xmsxData: {
        filterTypeList: []
      },
      visited: false,
      filter: {
        centerName: '',  // 中心 id
        centerId: -1,
        departId: -1,    // 部门 id
        departName: '',
        filterCenter: false,
        typeId: -1,  // 类型 id
        typeName: '',
        filterType: false,
        stateId: -1,  // 阶段 id
        stateName: '',
        filterState: false,
        riskId: -1,  // 风险 id
        riskName: '',
        filterRisk: false,
        projectId: -1,  // 状态 id
        projectName: '',
        filterProject: false
      }
    }
  }

  _tab(n) {
    if(n) {
      this.setState({
        showFilter: true,
        showSearch: false,
      });
    } else {
      this.setState({
        showFilter: false,
        showSearch: true,
      });
    }
  }

  _toSearch() {
    if(this.state.searchText) {
      store.dispatch(detailSearchResult({
        text: this.state.searchText
      }));

      this.props.router.push({
        pathname: '/xmsx/xmxq'
      })
    }
  }

  _toFilter() {
    if(this.state.filterData) {
      this.props.router.push({
        pathname: '/xmsx/sxjg'
      })
    }
  }

  _toChange(e) {
    this.setState({
      searchText: e.target.value
    })
  }

  // _toVisited(isBoolean) {
  //   console.log(isBoolean)
  //   this.setState({
  //     visited: isBoolean
  //   })
  // }

  componentWillMount() {
    let isVisitedSearchData = Immutable.Map(this.props.searchModule).toJS() ? Immutable.Map(this.props.searchModule).toJS() : false;
    // this.state.visited = isVisitedBoolean.data.filter.visited?isVisitedBoolean.data.filter.visited:false;
    let isVisitedSearchFilter = isVisitedSearchData.data.filter;
    // console.log(isVisitedBoolean)
    if(!Object.is(undefined, isVisitedSearchFilter)){
      this.state.visited = isVisitedSearchFilter.visited;
    }
    if(this.state.visited) {
      this.setState({
        configs: Object.assign({}, this.state.configs, {type: 'xmsxVisited'})
      },() => {
        // 判断是否已经选中条件
        // let flag = [filter.filterCenter, filter.filterDepartment, filter.filterProject, filter.filterRisk, filter.filterState, filter.filterType].some(item => item);
        // if(flag){
        //   _this.state.filterData = true;
        // }
      })
    }
  }

  componentDidMount() {
    // 同步测试
    // console.log(1111111)

    let isVisitedSearchData = Immutable.Map(this.props.searchModule).toJS() ? Immutable.Map(this.props.searchModule).toJS() : false;
    // this.state.visited = isVisitedBoolean.data.filter.visited?isVisitedBoolean.data.filter.visited:false;
    let isVisitedSearchFilter = isVisitedSearchData.data.filter;
    if(this.state.visited) {
        let _this = this,
            filter = isVisitedSearchFilter;
        let filterMaps = [
          {
            "key": "filterCenter",
            "value": ["centerName", "departName"],
          },
          {
            "key": "filterType",
            "value": "typeName"
          },
          {
            "key": "filterState",
            "value": "stateName"
          },
          {
            "key": "filterRisk",
            "value": "riskName"
          },
          {
            "key": "filterProject",
            "value": "projectName"
          }
        ];
        filterMaps.forEach( (item, i) => {
          // console.log(filter[item.key])
          if(i == 0){
            if(filter[item.key]){
              // console.log({[item.value[0]]: filter[item.value[0]]});


              // 调取action，
              // dispatch触发reducer
              // 但是不能同步
              //
              // store.dispatch({
              //   ...AddupChoiceText({
              //     [item.value[0]]: filter[item.value[0]] , [item.value[1]]: filter[item.value[1]],
              //     payload: () => { _this.state.configs.list = _this.props.searchModule.data.configs.list }
              //   }),
              // });

              // 方法二:reducer里回调同步
              // _this.props.AddupChoiceText({
              //   [item.value[0]]: filter[item.value[0]] , [item.value[1]]: filter[item.value[1]],
              //   payload: () => {
              //     _this.setState({
              //       configs: {
              //         list: _this.props.searchOverModule.data.configs.list,
              //         type: 'xmsxVisited'
              //       }
              //     }))
              //   }
              // });

              // 方法三:es7 async/await promise同步
              (async () => {
                await Promise.resolve(
                  _this.props.AddupChoiceText({
                    [item.value[0]]: filter[item.value[0]] , [item.value[1]]: filter[item.value[1]]
                  })
                )

                await Promise.resolve(
                  _this.setState({
                    configs: {
                      list: _this.props.searchOverModule.data.configs.list,
                      type: 'xmsxVisited'
                    }
                  })
                );
              })()


              // 早期方案直接修改state，
              // 但是不能同步
                // _this.setState({
                //   configs: {
                //     list: _this.props.searchModule.data
                //   }
                // }）
              // _this.configs.list[i].choiceCenter = filter[item.value[0]];
              // _this.configs.list[i].choiceDepart = filter[item.value[1]];
              //
            }
          }else{
            if(filter[item.key]){



              // store.dispatch({
              //   ...AddupChoiceText({
              //     [item.value]: filter[item.value],
              //     payload: () => { _this.state.configs.list = _this.props.searchModule.data.configs.list }
              //   })
              // });



              // _this.props.AddupChoiceText({
              //   [item.value]: filter[item.value],
              //   payload: () => {
              //     console.log(2222)
              //     _this.setState({
              //       configs: {
              //         list : _this.props.searchOverModule.data.configs.list,
              //         type: 'xmsxVisited'
              //       }
              //     }))
              //   }
              // });


              (async () => {
                await Promise.resolve(
                  _this.props.AddupChoiceText({
                    [item.value]: filter[item.value]
                  })
                )

                await Promise.resolve(
                  _this.setState({
                    configs: {
                      list : _this.props.searchOverModule.data.configs.list,
                      type: 'xmsxVisited'
                    }
                  })
                )
              })()


              // _this.configs.list[i].choiceText = filter[item.value];
              //
            }
          }
        });
        // console.log(_this)
        //第一种写法 Promise
        // _this.setState({
        //   configs: {
        //     list : _this.props.searchOverModule.data.configs.list,
        //     type: 'xmsxVisited'
        //   }
        // })

        // 判断是否已经选中条件
        let flag = [filter.filterCenter, filter.filterDepartment, filter.filterProject, filter.filterRisk, filter.filterState, filter.filterType].some(item => item);
        if(flag){
          _this.state.filterData = true;
        }
    }
  }

  renderCommonLists() {
    // console.log(this.state)
    return (
      <div className="main">
        <div className="nav-list">
          <div className="search-head">
            <span onClick={() => this._tab(1)} className={this.state.showFilter?"on filter":"filter"}>筛选</span>
            <span onClick={() => this._tab(0)} className={this.state.showSearch?"on search":"search"}>搜索</span>
          </div>
          <div className="clips"></div>
          <div className="content-box">
          {
            this.state.showFilter?<div className="switch-item">
              <CommonLists configs={this.state.configs}></CommonLists>
              <div className="btn-box">
                <button className={this.state.filterData?"on filterBtn":"filterBtn"} onClick={() => this._toFilter()}>筛选</button>
              </div>
            </div>:null
          }
          {
            this.state.showSearch?<div className="switch-item">
              <ul>
                <li className="search-li">
                  <em className="icon iconn-4"></em>
                  <input type="text" ref="searchText" placeholder="请输入项目名称" onChange={(e) => this._toChange(e)} value={this.state.searchText}/>
                </li>
              </ul>
              <div className="btn-box">
                <button className={this.state.searchText?"on searchBtn":"searchBtn"} onClick={() => this._toSearch()}>搜索</button>
              </div>
            </div>:null
          }
          </div>
        </div>
      </div>
    )
  }

  render() {
    return this.renderCommonLists();
  }
}

export default Connect({
  _id: 'xmsx',
  _component: Xmsx,
  _headerBackUrls: '/', //头部回退按钮地址
  _headerTitleSets: '筛选/搜索', //头部标题内容
});

// recode/JDP-vue 2/src/components/app/xmsx.vue
<template>
  <div class="main">
    <div class="nav-list">
      <div class="search-head">
        <span @click="tab(1)" :class="{filter:true, on:showFilter}">筛选</span>
        <span @click="tab(0)" :class="{search:true, on:showSearch}">搜索</span>
      </div>
      <div class="clips"></div>
      <div class="content-box">
        <div class="switch-item" v-show="showFilter">
          <commonLists :configs="configs"></commonLists>
          <div class="btn-box">
            <button :class="{filterBtn:true, on:filterData}" @click="toFilter">筛选</button>
          </div>
        </div>
        <div class="switch-item" v-show="showSearch">
          <ul>
            <li class="search-li">
              <em class="icon iconn-4"></em>
              <input type="text" placeholder="请输入项目名称" v-model="searchText" />
            </li>
          </ul>
          <div class="btn-box">
            <button :class="{searchBtn:true, on:searchText}" @click="toSearch">搜索</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import commonLists from '../widget/commonLists';
import { mapState } from 'vuex';
import store from '../../vuex';
export default {
  name: 'xmsx',
  data () {
    return {
      showFilter: true,
      showSearch: false,
      searchText: '',
      filterData: '',
      configs: {
        type: 'listNav',
        list: [
          {
            to: '/xmsx/option/1',
            text: '选择中心/部门'
          },
          {
            to: '/xmsx/option/2',
            text: '选择类型'
          },
          {
            to: '/xmsx/option/3',
            text: '选择阶段'
          },
          {
            to: '/xmsx/option/4',
            text: '选择风险类型'
          },
          {
            to: '/xmsx/option/5',
            text: '选择状态类型'
          },
        ]
      }
    }
  },
  methods: {
    tab(n){
      if(n){
        this.showFilter = true;
        this.showSearch = false;
      }else{
        this.showFilter = false;
        this.showSearch = true;
      }
    },
    toSearch(){
      if(this.searchText){
        this.$router.push({path:'/xmsx/xmxq'});
      }
    },
    toFilter(){
      if(this.filterData){
        this.$router.push({path:'/xmsx/sxjg'});
      }
    }
  },
  computed: mapState([
    'visited'
  ]),
  components: {
    commonLists
  },
  mounted(){
    let isVisited = store._modules.root.state.visited,
        filter = store._modules.root.state.filter,
        {centerId, centerName, departId, departName, id, text, choiceId} = this.$route.query;
    // 访问过了
    if(isVisited){
      console.log('访问过了');
      // 根据选中选项给 vuex 赋值
      switch(parseInt(id)){
        case 1:
          store.commit('filterCenter', {
            centerName,
            centerId,
            departId,
            departName,
            filterCenter: true
          });
          break;
        case 2:
          store.commit('filterType', {
            typeId: choiceId,
            typeName: text,
            filterType: true
          });
          break;
        case 3:
          store.commit('filterState', {
            stateId: choiceId,
            stateName: text,
            filterState: true,
          });
          break;
        case 4:
          store.commit('filterRisk', {
            riskId: choiceId,
            riskName: text,
            filterRisk: true,
          });
          break;
        case 5:
          store.commit('filterProject', {
            projectId: choiceId,
            projectName: text,
            filterProject: true
          });
          break;
      }
      /*if(id == 1){

      }else{

      }*/
      // 根据 vuex 的值 给页面填充选定文字
      let filterMaps = [
        {
          "key": "filterCenter",
          "value": ["centerName", "departName"],
        },
        {
          "key": "filterType",
          "value": "typeName"
        },
        {
          "key": "filterState",
          "value": "stateName"
        },
        {
          "key": "filterRisk",
          "value": "riskName"
        },
        {
          "key": "filterProject",
          "value": "projectName"
        }
      ],
          _this = this;

      //_this.configs.list = [];
      filterMaps.forEach( (item, i) => {
        if(i == 0){
          if(filter[item.key]){
            _this.configs.list[i].choiceText = filter[item.value[0]] + '/' + filter[item.value[1]];
          }
        }else{
          if(filter[item.key]){
            _this.configs.list[i].choiceText = filter[item.value];
          }
        }
      });
      // 判断是否已经选中条件
      let flag = [filter.filterCenter, filter.filterCenter, filter.filterCenter, filter.filterCenter, filter.filterCenter].some(item => item);
      if(flag){
        this.filterData = true;
      }
    }else{
      this.$router.push({path:'/xmsx'});
      console.log('nonooooo');
      store.commit('changeVisited');
      this.$http.get('/api/filterType').then(function (data){
        if(data.data.success){
          store.commit('getXmsxData', data.data.data);
        }else{
          console.log('error');
        }
      },function (err){
        console.log(err);
      });
    }
  }
}
</script>
