// recode/JDP-react/src/page/Component/xmsx.jsx
import React, { Component, PropTypes } from 'react';
import pureRender from 'pure-render-decorator';
import { History, Link } from 'react-router';
import Immutable, { is, fromJS } from 'immutable';

import store from '../Redux/Store';

import {detailSearchResult} from '../Redux/Action';

import CommonLists from './widget/commonLists';
import Connect from './connect/template';

class Xmsx extends Component {
  constructor(props, context) {
    super(props, context);

    this.state = {
      showFilter: true,
      showSearch: false,
      searchText: '',
      filterData: false,
      configs: {
        type: 'xmsx',
        list: [
          {
            to: '/xmsx/option/1',
            text: '选择中心/部门'
          },
          {
            to: '/xmsx/option/2',
            text: '选择类型'
          },
          {
            to: '/xmsx/option/3',
            text: '选择阶段'
          },
          {
            to: '/xmsx/option/4',
            text: '选择风险类型'
          },
          {
            to: '/xmsx/option/5',
            text: '选择状态类型'
          },
        ]
      },
      xmsxData: {
        filterTypeList: []
      },
      visited: false,
      filter: {
        centerName: '',  // 中心 id
        centerId: -1,
        departId: -1,    // 部门 id
        departName: '',
        filterCenter: false,
        typeId: -1,  // 类型 id
        typeName: '',
        filterType: false,
        stateId: -1,  // 阶段 id
        stateName: '',
        filterState: false,
        riskId: -1,  // 风险 id
        riskName: '',
        filterRisk: false,
        projectId: -1,  // 状态 id
        projectName: '',
        filterProject: false
      }
    }
  }

  _tab(n) {
    if(n) {
      this.setState({
        showFilter: true,
        showSearch: false,
      });
    } else {
      this.setState({
        showFilter: false,
        showSearch: true,
      });
    }
  }

  _toSearch() {
    if(this.state.searchText) {
      store.dispatch(detailSearchResult({
        text: this.state.searchText
      }));

      this.props.router.push({
        pathname: '/xmsx/xmxq'
      })
    }
  }

  _toFilter() {
    if(this.state.filterData) {
      this.props.router.push({
        pathname: '/xmsx/sxjg'
      })
    }
  }

  _toChange(e) {
    this.setState({
      searchText: e.target.value
    })
  }

  componentWillMount() {
    let isVisitedSearchData = Immutable.Map(this.props.searchModule).toJS() ? Immutable.Map(this.props.searchModule).toJS() : false;
    let isVisitedSearchFilter = isVisitedSearchData.data.filter;
    if(!Object.is(undefined, isVisitedSearchFilter)){
      this.state.visited = isVisitedSearchFilter.visited;
    }
    if(this.state.visited) {
      this.setState({
        configs: Object.assign({}, this.state.configs, {type: 'xmsxVisited'})
      },() => {
      })
    }
  }

  componentDidMount() {
    let isVisitedSearchData = Immutable.Map(this.props.searchModule).toJS() ? Immutable.Map(this.props.searchModule).toJS() : false;
    let isVisitedSearchFilter = isVisitedSearchData.data.filter;
    if(this.state.visited) {
        let _this = this,
            filter = isVisitedSearchFilter;
        let filterMaps = [
          {
            "key": "filterCenter",
            "value": ["centerName", "departName"],
          },
          {
            "key": "filterType",
            "value": "typeName"
          },
          {
            "key": "filterState",
            "value": "stateName"
          },
          {
            "key": "filterRisk",
            "value": "riskName"
          },
          {
            "key": "filterProject",
            "value": "projectName"
          }
        ];
        filterMaps.forEach( (item, i) => {
          if(i == 0){
            if(filter[item.key]){
              _this.props.AddupChoiceText({
                centerId: _this.props.searchModule.data.filter.centerId,
                [item.value[0]]: filter[item.value[0]] , [item.value[1]]: filter[item.value[1]],
                payload: () => {
                  _this.setState({
                    configs: {
                      list: _this.props.searchOverModule.data.configs.list,
                      type: 'xmsxVisited'
                    }
                  })
                }
              });
            }
          }else{
            if(filter[item.key]){
              _this.props.AddupChoiceText({
                centerId: _this.props.searchModule.data.filter.centerId,
                [item.value]: filter[item.value],
                payload: () => {
                  _this.setState({
                    configs: {
                      list : _this.props.searchOverModule.data.configs.list,
                      type: 'xmsxVisited'
                    }
                  })
                }
              });
            }
          }
        });

        // 判断是否已经选中条件
        let flag = [filter.filterCenter, filter.filterDepartment, filter.filterProject, filter.filterRisk, filter.filterState, filter.filterType].some(item => item);
        if(flag){
          _this.state.filterData = true;
        }
    }
  }

  renderCommonLists() {
    return (
      <div className="main">
        <div className="nav-list">
          <div className="search-head">
            <span onClick={() => this._tab(1)} className={this.state.showFilter?"on filter":"filter"}>筛选</span>
            <span onClick={() => this._tab(0)} className={this.state.showSearch?"on search":"search"}>搜索</span>
          </div>
          <div className="clips"></div>
          <div className="content-box">
          {
            this.state.showFilter?<div className="switch-item">
              <CommonLists configs={this.state.configs}></CommonLists>
              <div className="btn-box">
                <button className={this.state.filterData?"on filterBtn":"filterBtn"} onClick={() => this._toFilter()}>筛选</button>
              </div>
            </div>:null
          }
          {
            this.state.showSearch?<div className="switch-item">
              <ul>
                <li className="search-li">
                  <em className="icon iconn-4"></em>
                  <input type="text" ref="searchText" placeholder="请输入项目名称" onChange={(e) => this._toChange(e)} value={this.state.searchText}/>
                </li>
              </ul>
              <div className="btn-box">
                <button className={this.state.searchText?"on searchBtn":"searchBtn"} onClick={() => this._toSearch()}>搜索</button>
              </div>
            </div>:null
          }
          </div>
        </div>
      </div>
    )
  }

  render() {
    return this.renderCommonLists();
  }
}

export default Connect({
  _id: 'xmsx',
  _component: Xmsx,
  _headerBackUrls: '/', //头部回退按钮地址
  _headerTitleSets: '筛选/搜索', //头部标题内容
});

// recode/JDP-vue/src/components/app/general/xmsx.vue
<template>
  <div class="main">
    <div class="nav-list">
      <!-- <div class="search-head">
        <span @click="tab(1)" :class="{filter:true, on:showFilter}">筛选</span>
        <span @click="tab(0)" :class="{search:true, on:showSearch}">搜索</span>
      </div> -->
      <!-- <div class="clips"></div> -->
      <div class="content-box">
        <div class="switch-item" v-show="showFilter">
          <commonLists :configs="configs"></commonLists>
          <div class="btn-box">
            <button :class="{filterBtn:true, on:filterData}" @click="toFilter">筛选</button>
          </div>
        </div>
        <div class="switch-item" v-show="showSearch">
          <ul>
            <li class="search-li">
              <label for="searchText"><em class="icon iconn-4"></em></label>
              <input type="text" placeholder="请输入项目名称" v-model="searchText" id="searchText" />
            </li>
          </ul>
          <div class="btn-box">
            <button :class="{searchBtn:true, on:searchText}" @click="toSearch">搜索</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import commonLists from '../../widget/commonLists';
import { mapState } from 'vuex';
import store from '../../../vuex';
import API from '../../../utils/apis';
export default {
  name: 'xmsx',
  data () {
    return {
      showFilter: true,
      showSearch: false,
      searchText: '',
      filterData: false,
      configs: {
        type: 'xmsx',
        list: [
          {
            to: '/xmsx/option/1',
            text: '选择中心/部门'
          },
          {
            to: '/xmsx/option/2',
            text: '选择类型'
          },
          {
            to: '/xmsx/option/3',
            text: '选择阶段'
          },
          {
            to: '/xmsx/option/4',
            text: '选择风险类型'
          },
          {
            to: '/xmsx/option/5',
            text: '选择状态类型'
          },
        ]
      },
      isBackMain: false
    }
  },
  methods: {
    tab(n){
      if(n){
        this.showFilter = true;
        this.showSearch = false;
      }else{
        this.showFilter = false;
        this.showSearch = true;
      }
    },
    toSearch(){
      let _this = this;
      if(this.searchText){
        this.filterData = false;
        store.commit('setReffer', 'search');
        store.commit('setSearchText', _this.searchText);
        store.commit('initFilterData');
        store.commit('initProjectState');
        store.commit('setTurnToDetail', true);
        this.searchText = '';
        this.$router.push({path:'/xmsx/sxjg'});
      }
    },
    toFilter(){
      if(this.filterData){
        // store.commit('isSearchShow', 0);
        store.commit('setIsZxReferer', false);
        store.commit('initProjectState');
        store.commit('setReffer', 'filter');
        store.commit('setTurnToDetail', true);
        this.$router.push({path:'/xmsx/sxjg'});
      }
    }
  },
  computed:{
    ...mapState({
      visited:state=>state.xmsxModule.visited,
      xmsxData:state=>state.xmsxModule.xmsxData,
      isVisited:state=>state.xmsxModule.visited,
      filter:state=>state.xmsxModule.filter,
      projectName:state=>state.curProject.curName
    })
  },
  components: {
    commonLists
  },
  created(){
    let _this = this,
        {centerId, centerName, departId, departName, id, text, choiceId} = this.$route.query;
    // 访问过了
    if(this.isVisited){
      let filter = _this.filter;
      _this.configs.type = 'xmsxVisited';
      // console.log('访问过了, 这个日志请忽略 勿删');
      // 根据 vuex 的值 给页面填充选定文字
      let filterMaps = [
        {
          "key": "filterCenter",
          "value": ["centerName", "departName"],
        },
        {
          "key": "filterType",
          "value": "typeName"
        },
        {
          "key": "filterState",
          "value": "stateName"
        },
        {
          "key": "filterRisk",
          "value": "riskName"
        },
        {
          "key": "filterProject",
          "value": "projectName"
        }
      ];
      filterMaps.forEach( (item, i) => {
        if(i == 0){
          if(filter[item.key]){
            _this.configs.list[i].choiceCenter = filter[item.value[0]];
            _this.configs.list[i].choiceDepart = filter[item.value[1]];
          }
        }else{
          if(filter[item.key]){
            _this.configs.list[i].choiceText = filter[item.value];
          }
        }
      });
      // 判断是否已经选中条件
      let flag = [filter.filterCenter, filter.filterDepartment, filter.filterProject, filter.filterRisk, filter.filterState, filter.filterType].some(item => item);
      if(flag){
        _this.filterData = true;
      }
    }else{
      this.$router.replace({path:'/xmsx'});
      // console.log('第一次访问, 这个日志请忽略 勿删');
      store.commit('changeVisited');
      this.$http.get(API('filterType')).then(function (data){
        if(data.data.success){
          store.commit('getXmsxData', data.data.data);
        }else{
          console.log('error');
        }
      },function (err){
        console.log(err);
      });
    }
    window.onpopstate = function (){
      if(/xmsx\/option\/\d(\/\d+)?/.test(_this.$route.path)){
        if(_this.isBackIndex){
          window.location.href = _this.$store.state.curProject.mainReffer;
        }else if(_this.isBackMain){
          _this.$router.push({path:'/api/projectCnt'});
          _this.isBackIndex = true;
        }else{
          _this.isBackMain = true;
          _this.$router.push({path:'/main'});
        }
      }
    };
  }
}
</script>
